FROM mcr.microsoft.com/playwright:v1.61.1-noble
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY tsconfig.json playwright.config.ts tsconfig.e2e.json ./
COPY e2e/ ./e2e/
CMD ["npx", "playwright", "test", "--reporter=list"]
